#!/usr/bin/env python3
"""Search exact-game networks generated by legal witness-point deletions."""

from __future__ import annotations

import argparse
import itertools
import json
import random
import sys
from fractions import Fraction
from pathlib import Path

sys.path.insert(
    0,
    "/Users/maxf/projects/economics-research/game-theory/"
    "exact-game-monotone-selection/src",
)

from family_search import game_from_points
from n5_sparse_family_lp import sparse_family_slack_float
from nonlarge_basis_search import basis_game


F = Fraction
N = 5


def compositions(total: int):
    for cuts in itertools.combinations(range(total + N - 1), N - 1):
        values = []
        previous = -1
        for cut in (*cuts, total + N - 1):
            values.append(cut - previous - 1)
            previous = cut
        yield tuple(F(value) for value in values)


def connected_components(
    node_count: int, edges: set[tuple[int, int, int]]
) -> list[tuple[list[int], list[tuple[int, int, int]]]]:
    adjacency = [set() for _ in range(node_count)]
    for lower, upper, _coalition in edges:
        adjacency[lower].add(upper)
        adjacency[upper].add(lower)
    unseen = set(range(node_count))
    result = []
    while unseen:
        root = unseen.pop()
        nodes = [root]
        stack = [root]
        while stack:
            node = stack.pop()
            for neighbor in adjacency[node]:
                if neighbor in unseen:
                    unseen.remove(neighbor)
                    nodes.append(neighbor)
                    stack.append(neighbor)
        if len(nodes) < 2:
            continue
        keep = set(nodes)
        local_index = {node: index for index, node in enumerate(nodes)}
        local_edges = [
            (local_index[lower], local_index[upper], coalition)
            for lower, upper, coalition in edges
            if lower in keep and upper in keep
        ]
        result.append((nodes, local_edges))
    result.sort(key=lambda item: (len(item[0]), len(item[1])), reverse=True)
    return result


def build(points):
    game_index = {}
    games = []
    state_game = {}
    for state in range(1, 1 << len(points)):
        game = game_from_points(
            [points[index] for index in range(len(points)) if state >> index & 1]
        )
        if game not in game_index:
            game_index[game] = len(games)
            games.append(game)
        state_game[state] = game_index[game]
    edges = set()
    for state in range(1, 1 << len(points)):
        lower = state_game[state]
        for removed in range(len(points)):
            if not state >> removed & 1 or state == 1 << removed:
                continue
            upper = state_game[state ^ (1 << removed)]
            if lower == upper:
                continue
            differences = [
                coalition
                for coalition, (before, after) in enumerate(
                    zip(games[lower], games[upper], strict=True)
                )
                if before != after
            ]
            if len(differences) != 1:
                continue
            coalition = differences[0]
            if coalition not in (0, (1 << N) - 1) and games[lower][coalition] < games[upper][coalition]:
                edges.add((lower, upper, coalition))
    grand = (1 << N) - 1
    for coalition in range(1, grand):
        groups = {}
        for index, game in enumerate(games):
            signature = game[:coalition] + game[coalition + 1 :]
            groups.setdefault(signature, []).append(index)
        for indices in groups.values():
            if len(indices) < 2:
                continue
            ordered = sorted(indices, key=lambda index: games[index][coalition])
            for lower_position, lower in enumerate(ordered):
                for upper in ordered[lower_position + 1 :]:
                    edges.add((lower, upper, coalition))
    return games, edges


def main() -> int:
    global N
    parser = argparse.ArgumentParser()
    parser.add_argument("--n", type=int, default=5)
    parser.add_argument("--trials", type=int, default=100)
    parser.add_argument("--point-count", type=int, default=10)
    parser.add_argument("--total", type=int, default=6)
    parser.add_argument("--coordinate-bound", type=int, default=0)
    parser.add_argument("--basis-points", type=int, default=0)
    parser.add_argument("--bppv-points", action="store_true")
    parser.add_argument("--seed", type=int, default=20260731)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    N = args.n
    rng = random.Random(args.seed)
    if args.bppv_points:
        if N != 5:
            raise ValueError("the BPPV point orbit is five-player")
        pool = list(
            {
                tuple(F(point[index]) for index in permutation)
                for point in ((3, 1, 1, 2, 2), (2, 3, 2, 1, 1))
                for permutation in itertools.permutations(range(N))
            }
        )
    elif args.basis_points:
        point_pool = set()
        grand = (1 << N) - 1
        while len(point_pool) < args.basis_points:
            result = basis_game(
                tuple(sorted(rng.sample(range(1, grand), N))), N
            )
            if result is not None:
                point_pool.update(result[0])
        pool = list(point_pool)
    else:
        pool = list(compositions(args.total)) if not args.coordinate_bound else []
    summaries = []
    best = None
    for trial in range(args.trials):
        if args.bppv_points or args.basis_points:
            points = rng.sample(pool, args.point_count)
        elif args.coordinate_bound:
            point_set = set()
            while len(point_set) < args.point_count:
                prefix = tuple(
                    F(rng.randint(-args.coordinate_bound, args.coordinate_bound))
                    for _ in range(N - 1)
                )
                point_set.add(prefix + (F(args.total) - sum(prefix),))
            points = list(point_set)
        else:
            points = rng.sample(pool, args.point_count)
        games, edges = build(points)
        components = connected_components(len(games), edges)
        trial_best = None
        for nodes, local_edges in components[:10]:
            local_games = [games[node] for node in nodes]
            margin = sparse_family_slack_float(local_games, local_edges, N)
            if margin is None:
                continue
            if trial_best is None or margin < trial_best[0]:
                trial_best = (margin, nodes, local_edges)
            if best is None or margin < best[0]:
                best = (margin, points, local_games, local_edges)
            if margin < -1e-8:
                break
        summary = {
            "trial": trial,
            "distinct_games": len(games),
            "legal_edges": len(edges),
            "component_count": len(components),
            "largest_component": len(components[0][0]) if components else 0,
            "largest_component_edges": len(components[0][1]) if components else 0,
            "largest_component_cycle_rank": (
                len(components[0][1]) - len(components[0][0]) + 1
                if components
                else 0
            ),
            "margin": None if trial_best is None else trial_best[0],
        }
        summaries.append(summary)
        print(json.dumps(summary), flush=True)
        if trial_best is not None and trial_best[0] < -1e-8:
            break
    payload = {
        "status": (
            "incompatible_exact_family_found"
            if best is not None and best[0] < -1e-8
            else "no_incompatible_exact_family_found"
        ),
        "configuration": vars(args) | {"output": str(args.output)},
        "summaries": summaries,
        "best": None
        if best is None
        else {
            "margin": best[0],
            "points": [[str(value) for value in point] for point in best[1]],
            "games": [[str(value) for value in game] for game in best[2]],
            "edges": [list(edge) for edge in best[3]],
        },
    }
    args.output.write_text(json.dumps(payload, indent=2) + "\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
