#!/usr/bin/env python3
"""Search subset families generated by the six-player Lmax witness orbit."""

from __future__ import annotations

import argparse
import itertools
import json
import random
import sys
from fractions import Fraction
from pathlib import Path

sys.path.insert(
    0,
    "/Users/maxf/projects/economics-research/game-theory/"
    "exact-game-monotone-selection/src",
)

import n5_point_deletion_family_search as deletion
from n5_sparse_family_lp import sparse_family_slack_float


F = Fraction
N = 6


def orbit_points() -> list[tuple[F, ...]]:
    seeds = (
        (F(4), F(2), F(5), F(12), F(19), F(9)),
        (F(17), F(25), F(2), F(1), F(6), F(0)),
        (F(10), F(11), F(2), F(9), F(13), F(6)),
        (F(19, 2), F(41, 4), F(9, 4), F(37, 4), F(27, 2), F(25, 4)),
    )
    return sorted(
        {
            tuple(seed[index] for index in permutation)
            for seed in seeds
            for permutation in itertools.permutations(range(N))
        }
    )


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--trials", type=int, default=50)
    parser.add_argument("--point-count", type=int, default=10)
    parser.add_argument("--permutation-blocks", type=int, default=0)
    parser.add_argument("--seed", type=int, default=20260731)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    deletion.N = N
    rng = random.Random(args.seed)
    pool = orbit_points()
    mandatory = (
        (F(4), F(2), F(5), F(12), F(19), F(9)),
        (F(17), F(25), F(2), F(1), F(6), F(0)),
        (F(10), F(11), F(2), F(9), F(13), F(6)),
        (F(19, 2), F(41, 4), F(9, 4), F(37, 4), F(27, 2), F(25, 4)),
    )
    rows = []
    best = None
    for trial in range(args.trials):
        if args.permutation_blocks:
            permutations = [tuple(range(N))] + rng.sample(
                list(itertools.permutations(range(N)))[1:],
                args.permutation_blocks - 1,
            )
            points = list(
                {
                    tuple(point[index] for index in permutation)
                    for point in mandatory
                    for permutation in permutations
                }
            )
        else:
            extras = rng.sample(
                [point for point in pool if point not in mandatory],
                args.point_count - len(mandatory),
            )
            points = list(mandatory) + extras
        games, edges = deletion.build(points)
        components = deletion.connected_components(len(games), edges)
        trial_best = None
        for nodes, local_edges in components[:10]:
            margin = sparse_family_slack_float(
                [games[node] for node in nodes], local_edges, N
            )
            if margin is None:
                continue
            if trial_best is None or margin < trial_best[0]:
                trial_best = (margin, nodes, local_edges)
            if best is None or margin < best[0]:
                best = (margin, points, [games[node] for node in nodes], local_edges)
            if margin < -1e-8:
                break
        row = {
            "trial": trial,
            "games": len(games),
            "edges": len(edges),
            "largest_component": len(components[0][0]) if components else 0,
            "margin": None if trial_best is None else trial_best[0],
        }
        rows.append(row)
        print(json.dumps(row), flush=True)
        if trial_best is not None and trial_best[0] < -1e-8:
            break
    payload = {
        "status": (
            "incompatible_exact_family_found"
            if best is not None and best[0] < -1e-8
            else "no_incompatible_exact_family_found"
        ),
        "rows": rows,
        "best": None
        if best is None
        else {
            "margin": best[0],
            "points": [[str(value) for value in point] for point in best[1]],
            "games": [[str(value) for value in game] for game in best[2]],
            "edges": [list(edge) for edge in best[3]],
        },
    }
    args.output.write_text(json.dumps(payload, indent=2) + "\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
